In [3]:
import datetime
from datetime import date
from pandas.tseries.offsets import *
import pandas as pd

In [4]:
d = date(2012,1,1)+ DateOffset(months=-6)
str(d.strftime(format='%Y%m%d'))

'20110701'

In [20]:
# lagging with one month gap
offset= 12
counter = 0
for year in range(2012,2019):
    for month in range(1,13):
        d = date(year,month,1)
        d3 = d+DateOffset(months=-1)
        d2 = d+DateOffset(months=-(offset+1))
        if counter == 0:
            print("drop table if exists lagging_feature_gap_%d;\n" % offset)
            print('create table if not exists lagging_feature_gap_%d as' % offset)
        else:
            print('insert into lagging_feature_gap_%d' % offset)
        print("select province_id, city_id, class_id, to_date('%s','yyyymmdd') as sale_date, avg(sale_quantity) as avg_%d,median(sale_quantity) as med_%d, max(sale_quantity) as max_%d, min(sale_quantity) as min_%d,stddev(sale_quantity) as std_%d, count(sale_quantity) as count_%d" \
             %(d.strftime(format='%Y%m%d'), offset,offset,offset,offset,offset,offset))
        print('from yc_car_sales_grouped a')
        print("where a.sale_date<to_date('%s','yyyymmdd') and a.sale_date>=to_date('%s','yyyymmdd')"%(d3.strftime(format='%Y%m%d'),d2.strftime(format='%Y%m%d')))
        print("group by province_id, city_id, class_id;\n")
        counter+=1
        
        if year==2018 and month==2:
            break

drop table if exists lagging_feature_gap_12;

create table if not exists lagging_feature_gap_12 as
select province_id, city_id, class_id, to_date('20120101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20111201','yyyymmdd') and a.sale_date>=to_date('20101201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20120201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120101','yyyymmdd') and a.sale_date>=to_date('20110101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20120301','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120201','yyyymmdd') and a.sale_date>=to_date('20110201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20120401','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120301','yyyymmdd') and a.sale_date>=to_date('20110301','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20120501','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120401','yyyymmdd') and a.sale_date>=to_date('20110401','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20120601','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120501','yyyymmdd') and a.sale_date>=to_date('20110501','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20120701','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120601','yyyymmdd') and a.sale_date>=to_date('20110601','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20120801','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120701','yyyymmdd') and a.sale_date>=to_date('20110701','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20120901','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120801','yyyymmdd') and a.sale_date>=to_date('20110801','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20121001','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20120901','yyyymmdd') and a.sale_date>=to_date('20110901','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20121101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20121001','yyyymmdd') and a.sale_date>=to_date('20111001','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20121201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20121101','yyyymmdd') and a.sale_date>=to_date('20111101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20121201','yyyymmdd') and a.sale_date>=to_date('20111201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130101','yyyymmdd') and a.sale_date>=to_date('20120101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130301','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130201','yyyymmdd') and a.sale_date>=to_date('20120201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130401','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130301','yyyymmdd') and a.sale_date>=to_date('20120301','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130501','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130401','yyyymmdd') and a.sale_date>=to_date('20120401','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130601','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130501','yyyymmdd') and a.sale_date>=to_date('20120501','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130701','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130601','yyyymmdd') and a.sale_date>=to_date('20120601','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130801','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130701','yyyymmdd') and a.sale_date>=to_date('20120701','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20130901','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130801','yyyymmdd') and a.sale_date>=to_date('20120801','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20131001','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20130901','yyyymmdd') and a.sale_date>=to_date('20120901','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20131101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20131001','yyyymmdd') and a.sale_date>=to_date('20121001','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20131201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20131101','yyyymmdd') and a.sale_date>=to_date('20121101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20131201','yyyymmdd') and a.sale_date>=to_date('20121201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140101','yyyymmdd') and a.sale_date>=to_date('20130101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140301','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140201','yyyymmdd') and a.sale_date>=to_date('20130201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140401','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140301','yyyymmdd') and a.sale_date>=to_date('20130301','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140501','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140401','yyyymmdd') and a.sale_date>=to_date('20130401','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140601','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140501','yyyymmdd') and a.sale_date>=to_date('20130501','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140701','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140601','yyyymmdd') and a.sale_date>=to_date('20130601','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140801','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140701','yyyymmdd') and a.sale_date>=to_date('20130701','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20140901','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140801','yyyymmdd') and a.sale_date>=to_date('20130801','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20141001','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20140901','yyyymmdd') and a.sale_date>=to_date('20130901','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20141101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20141001','yyyymmdd') and a.sale_date>=to_date('20131001','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20141201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20141101','yyyymmdd') and a.sale_date>=to_date('20131101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20150101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20141201','yyyymmdd') and a.sale_date>=to_date('20131201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20150201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20150101','yyyymmdd') and a.sale_date>=to_date('20140101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20150301','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20150201','yyyymmdd') and a.sale_date>=to_date('20140201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20150401','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20150301','yyyymmdd') and a.sale_date>=to_date('20140301','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20150501','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20150401','yyyymmdd') and a.sale_date>=to_date('20140401','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12
select province_id, city_id, class_id, to_date('20150601','yyyymmdd') as sale_date, avg(sale_quantity) as avg_12,median(sale_quantity) as med_12, max(sale_quantity) as max_12, min(sale_quantity) as min_12,stddev(sale_quantity) as std_12, count(sale_quantity) as count_12
from yc_car_sales_grouped a
where a.sale_date<to_date('20150501','yyyymmdd') and a.sale_date>=to_date('20140501','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_gap_12

In [65]:
offset= 2
counter = 0
for year in range(2012,2019):
    for month in range(1,13):
        d = date(year,month,1)
        d2 = d+DateOffset(months=-offset)
        if counter == 0:
            print("drop table if exists lagging_feature_%d;\n" % offset)
            print('create table if not exists lagging_feature_%d as' % offset)
        else:
            print('insert into lagging_feature_%d' % offset)
        print("select province_id, city_id, class_id, to_date('%s','yyyymmdd') as sale_date, avg(sale_quantity) as avg_%d,median(sale_quantity) as med_%d, max(sale_quantity) as max_%d, min(sale_quantity) as min_%d,stddev(sale_quantity) as std_%d, count(sale_quantity) as count_%d" \
             %(d.strftime(format='%Y%m%d'), offset,offset,offset,offset,offset,offset))
        print('from yc_car_sales_grouped a')
        print("where a.sale_date<to_date('%s','yyyymmdd') and a.sale_date>=to_date('%s','yyyymmdd')"%(d.strftime(format='%Y%m%d'),d2.strftime(format='%Y%m%d')))
        print("group by province_id, city_id, class_id;\n")
        counter+=1
        
        if year==2018 and month==1:
            break

drop table if exists lagging_feature_2;

create table if not exists lagging_feature_2 as
select province_id, city_id, class_id, to_date('20120101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120101','yyyymmdd') and a.sale_date>=to_date('20111101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20120201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120201','yyyymmdd') and a.sale_date>=to_date('20111201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20120301','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120301','yyyymmdd') and a.sale_date>=to_date('20120101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20120401','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120401','yyyymmdd') and a.sale_date>=to_date('20120201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20120501','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120501','yyyymmdd') and a.sale_date>=to_date('20120301','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20120601','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120601','yyyymmdd') and a.sale_date>=to_date('20120401','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20120701','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120701','yyyymmdd') and a.sale_date>=to_date('20120501','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20120801','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120801','yyyymmdd') and a.sale_date>=to_date('20120601','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20120901','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20120901','yyyymmdd') and a.sale_date>=to_date('20120701','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20121001','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20121001','yyyymmdd') and a.sale_date>=to_date('20120801','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20121101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20121101','yyyymmdd') and a.sale_date>=to_date('20120901','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20121201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20121201','yyyymmdd') and a.sale_date>=to_date('20121001','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130101','yyyymmdd') and a.sale_date>=to_date('20121101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130201','yyyymmdd') and a.sale_date>=to_date('20121201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130301','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130301','yyyymmdd') and a.sale_date>=to_date('20130101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130401','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130401','yyyymmdd') and a.sale_date>=to_date('20130201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130501','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130501','yyyymmdd') and a.sale_date>=to_date('20130301','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130601','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130601','yyyymmdd') and a.sale_date>=to_date('20130401','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130701','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130701','yyyymmdd') and a.sale_date>=to_date('20130501','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130801','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130801','yyyymmdd') and a.sale_date>=to_date('20130601','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20130901','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20130901','yyyymmdd') and a.sale_date>=to_date('20130701','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20131001','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20131001','yyyymmdd') and a.sale_date>=to_date('20130801','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20131101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20131101','yyyymmdd') and a.sale_date>=to_date('20130901','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20131201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20131201','yyyymmdd') and a.sale_date>=to_date('20131001','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140101','yyyymmdd') and a.sale_date>=to_date('20131101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140201','yyyymmdd') and a.sale_date>=to_date('20131201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140301','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140301','yyyymmdd') and a.sale_date>=to_date('20140101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140401','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140401','yyyymmdd') and a.sale_date>=to_date('20140201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140501','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140501','yyyymmdd') and a.sale_date>=to_date('20140301','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140601','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140601','yyyymmdd') and a.sale_date>=to_date('20140401','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140701','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140701','yyyymmdd') and a.sale_date>=to_date('20140501','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140801','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140801','yyyymmdd') and a.sale_date>=to_date('20140601','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20140901','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20140901','yyyymmdd') and a.sale_date>=to_date('20140701','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20141001','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20141001','yyyymmdd') and a.sale_date>=to_date('20140801','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20141101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20141101','yyyymmdd') and a.sale_date>=to_date('20140901','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20141201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20141201','yyyymmdd') and a.sale_date>=to_date('20141001','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20150101','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20150101','yyyymmdd') and a.sale_date>=to_date('20141101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20150201','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20150201','yyyymmdd') and a.sale_date>=to_date('20141201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20150301','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20150301','yyyymmdd') and a.sale_date>=to_date('20150101','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20150401','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20150401','yyyymmdd') and a.sale_date>=to_date('20150201','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20150501','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20150501','yyyymmdd') and a.sale_date>=to_date('20150301','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20150601','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20150601','yyyymmdd') and a.sale_date>=to_date('20150401','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2
select province_id, city_id, class_id, to_date('20150701','yyyymmdd') as sale_date, avg(sale_quantity) as avg_2,median(sale_quantity) as med_2, max(sale_quantity) as max_2, min(sale_quantity) as min_2,stddev(sale_quantity) as std_2, count(sale_quantity) as count_2
from yc_car_sales_grouped a
where a.sale_date<to_date('20150701','yyyymmdd') and a.sale_date>=to_date('20150501','yyyymmdd')
group by province_id, city_id, class_id;

insert into lagging_feature_2

In [6]:
# last month
offset= 1
counter = 0
for year in range(2012,2019):
    for month in range(1,13):
        d = date(year,month,1)
        d2 = d+DateOffset(months=-offset)
        if counter == 0:
            print("drop table if exists last_month;\n")
            print('create table if not exists last_month as')
        else:
            print('insert into last_month')
        print("select province_id, city_id, class_id, to_date('%s','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale" \
             %(d.strftime(format='%Y%m%d')))
        print('from yc_car_sales_grouped a')
        print("where a.sale_date=to_date('%s','yyyymmdd')"%(d2.strftime(format='%Y%m%d')))
        print("group by province_id, city_id, class_id;\n")
        counter+=1
        
        if year==2018 and month==1:
            break

drop table if exists last_month;

create table if not exists last_month as
select province_id, city_id, class_id, to_date('20120101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20120201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20120301','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20120401','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20120501','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20120601','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20120701','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20120801','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20120901','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20121001','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20121101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20121201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130301','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130401','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130501','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130601','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130701','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130801','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20130901','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20131001','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20131101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20131201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140301','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140401','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140501','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140601','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140701','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140801','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20140901','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20141001','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20141101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20141201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150301','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150401','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150501','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150601','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150701','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150801','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20150901','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20151001','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20151101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20151201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160301','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160401','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160501','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160601','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160701','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160801','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20160901','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20161001','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20161101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20161201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170301','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170401','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170501','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170601','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170701','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170801','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20170901','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20171001','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20171101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20171001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20171201','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20171101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_month
select province_id, city_id, class_id, to_date('20180101','yyyymmdd') as sale_date, avg(sale_quantity) as lm_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20171201','yyyymmdd')
group by province_id, city_id, class_id;

In [14]:
# last 2 month
offset= 2
counter = 0
for year in range(2012,2019):
    for month in range(1,13):
        d = date(year,month,1)
        d2 = d+DateOffset(months=-offset)
        if counter == 0:
            print("drop table if exists last_2_month;\n")
            print('create table if not exists last_2_month as')
        else:
            print('insert into last_2_month')
        print("select province_id, city_id, class_id, to_date('%s','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale" \
             %(d.strftime(format='%Y%m%d')))
        print('from yc_car_sales_grouped a')
        print("where a.sale_date=to_date('%s','yyyymmdd')"%(d2.strftime(format='%Y%m%d')))
        print("group by province_id, city_id, class_id;\n")
        counter+=1
        
        if year==2018 and month==2:
            break

drop table if exists last_2_month;

create table if not exists last_2_month as
select province_id, city_id, class_id, to_date('20120101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20120201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20120301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20120401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20120501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20120601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20120701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20120801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20120901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20121001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20121101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20121201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20130901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20131001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20131101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20131201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20140901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20141001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20141101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20141201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20150901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20151001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20151101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20151201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20160901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20161001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20161101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20161201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20170901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20171001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20171101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20171201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20171001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20180101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20171101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_2_month
select province_id, city_id, class_id, to_date('20180201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20171201','yyyymmdd')
group by province_id, city_id, class_id;

In [15]:
# last 3 month
offset= 3
counter = 0
for year in range(2012,2019):
    for month in range(1,13):
        d = date(year,month,1)
        d2 = d+DateOffset(months=-offset)
        if counter == 0:
            print("drop table if exists last_3_month;\n")
            print('create table if not exists last_3_month as')
        else:
            print('insert into last_3_month')
        print("select province_id, city_id, class_id, to_date('%s','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale" \
             %(d.strftime(format='%Y%m%d')))
        print('from yc_car_sales_grouped a')
        print("where a.sale_date=to_date('%s','yyyymmdd')"%(d2.strftime(format='%Y%m%d')))
        print("group by province_id, city_id, class_id;\n")
        counter+=1
        
        if year==2018 and month==2:
            break

drop table if exists last_3_month;

create table if not exists last_3_month as
select province_id, city_id, class_id, to_date('20120101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20120201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20120301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20120401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20120501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20120601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20120701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20120801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20120901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20121001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20121101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20121201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20130901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20131001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20131101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20131201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20140901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20141001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20141101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20141201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20150901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20151001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20151101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20151201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20160901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20161001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20161101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20161201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170301','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170401','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170501','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170601','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170701','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170801','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20170901','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20171001','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20171101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20171201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20180101','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20171001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_3_month
select province_id, city_id, class_id, to_date('20180201','yyyymmdd') as sale_date, avg(sale_quantity) as l2m_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20171101','yyyymmdd')
group by province_id, city_id, class_id;

In [16]:
# last year
offset= 12
counter = 0
for year in range(2012,2019):
    for month in range(1,13):
        d = date(year,month,1)
        d2 = d+DateOffset(months=-offset)
        if counter == 0:
            print("drop table if exists last_year;\n")
            print('create table if not exists last_year as')
        else:
            print('insert into last_year')
        print("select province_id, city_id, class_id, to_date('%s','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale" \
             %(d.strftime(format='%Y%m%d')))
        print('from yc_car_sales_grouped a')
        print("where a.sale_date=to_date('%s','yyyymmdd')"%(d2.strftime(format='%Y%m%d')))
        print("group by province_id, city_id, class_id;\n")
        counter+=1
        
        if year==2018 and month==2:
            break

drop table if exists last_year;

create table if not exists last_year as
select province_id, city_id, class_id, to_date('20120101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20120201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20120301','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20120401','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20120501','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20120601','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20120701','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20120801','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20120901','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20110901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20121001','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20121101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20121201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20111201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130301','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130401','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130501','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130601','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130701','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130801','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20130901','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20120901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20131001','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20131101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20131201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20121201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140301','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140401','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140501','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140601','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140701','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140801','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20140901','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20130901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20141001','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20141101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20141201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20131201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150301','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150401','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150501','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150601','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150701','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150801','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20150901','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20140901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20151001','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20151101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20151201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20141201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160301','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160401','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160501','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160601','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160701','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160801','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20160901','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20150901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20161001','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20161101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20161201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20151201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170301','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160301','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170401','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160401','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170501','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160501','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170601','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160601','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170701','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160701','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170801','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160801','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20170901','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20160901','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20171001','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161001','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20171101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20171201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20161201','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20180101','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170101','yyyymmdd')
group by province_id, city_id, class_id;

insert into last_year
select province_id, city_id, class_id, to_date('20180201','yyyymmdd') as sale_date, avg(sale_quantity) as ly_sale
from yc_car_sales_grouped a
where a.sale_date=to_date('20170201','yyyymmdd')
group by province_id, city_id, class_id;

In [44]:
offset= 6
counter = 0
for year in range(2012,2018):
    for month in range(1,13):
        d = date(year,month,1)
        d2 = d+DateOffset(months=-offset)
        if counter == 0:
            print('create table if not exists lagging_feature_noclass_%d as' % offset)
        else:
            print('insert into lagging_feature_noclass_%d' % offset)
        print("select province_id, city_id, to_date('%s','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_%d, avg(sale_quantity) as navg_%d,median(sale_quantity) as nmed_%d, stddev(sale_quantity) as nstd_%d" \
             %(d.strftime(format='%Y%m%d'), offset,offset,offset,offset))
        print('from yc_car_sales_grouped')
        print("where sale_date<to_date('%s','yyyymmdd') and sale_date>=to_date('%s','yyyymmdd')"%(d.strftime(format='%Y%m%d'),d2.strftime(format='%Y%m%d')))
        print("group by province_id, city_id;\n")
        counter+=1

create table if not exists lagging_feature_noclass_6 as
select province_id, city_id, to_date('20120101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120101','yyyymmdd') and sale_date>=to_date('20110701','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20120201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120201','yyyymmdd') and sale_date>=to_date('20110801','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20120301','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120301','yyyymmdd') and sale_date>=to_date('20110901','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20120401','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120401','yyyymmdd') and sale_date>=to_date('20111001','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20120501','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120501','yyyymmdd') and sale_date>=to_date('20111101','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20120601','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120601','yyyymmdd') and sale_date>=to_date('20111201','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20120701','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120701','yyyymmdd') and sale_date>=to_date('20120101','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20120801','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120801','yyyymmdd') and sale_date>=to_date('20120201','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20120901','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20120901','yyyymmdd') and sale_date>=to_date('20120301','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20121001','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20121001','yyyymmdd') and sale_date>=to_date('20120401','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20121101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20121101','yyyymmdd') and sale_date>=to_date('20120501','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20121201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20121201','yyyymmdd') and sale_date>=to_date('20120601','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130101','yyyymmdd') and sale_date>=to_date('20120701','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130201','yyyymmdd') and sale_date>=to_date('20120801','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130301','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130301','yyyymmdd') and sale_date>=to_date('20120901','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130401','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130401','yyyymmdd') and sale_date>=to_date('20121001','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130501','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130501','yyyymmdd') and sale_date>=to_date('20121101','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130601','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130601','yyyymmdd') and sale_date>=to_date('20121201','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130701','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130701','yyyymmdd') and sale_date>=to_date('20130101','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130801','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130801','yyyymmdd') and sale_date>=to_date('20130201','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20130901','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20130901','yyyymmdd') and sale_date>=to_date('20130301','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20131001','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20131001','yyyymmdd') and sale_date>=to_date('20130401','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20131101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20131101','yyyymmdd') and sale_date>=to_date('20130501','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20131201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20131201','yyyymmdd') and sale_date>=to_date('20130601','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140101','yyyymmdd') and sale_date>=to_date('20130701','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140201','yyyymmdd') and sale_date>=to_date('20130801','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140301','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140301','yyyymmdd') and sale_date>=to_date('20130901','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140401','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140401','yyyymmdd') and sale_date>=to_date('20131001','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140501','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140501','yyyymmdd') and sale_date>=to_date('20131101','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140601','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140601','yyyymmdd') and sale_date>=to_date('20131201','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140701','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140701','yyyymmdd') and sale_date>=to_date('20140101','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140801','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140801','yyyymmdd') and sale_date>=to_date('20140201','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20140901','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20140901','yyyymmdd') and sale_date>=to_date('20140301','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20141001','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20141001','yyyymmdd') and sale_date>=to_date('20140401','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20141101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20141101','yyyymmdd') and sale_date>=to_date('20140501','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20141201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20141201','yyyymmdd') and sale_date>=to_date('20140601','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150101','yyyymmdd') and sale_date>=to_date('20140701','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150201','yyyymmdd') and sale_date>=to_date('20140801','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150301','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150301','yyyymmdd') and sale_date>=to_date('20140901','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150401','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150401','yyyymmdd') and sale_date>=to_date('20141001','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150501','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150501','yyyymmdd') and sale_date>=to_date('20141101','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150601','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150601','yyyymmdd') and sale_date>=to_date('20141201','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150701','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150701','yyyymmdd') and sale_date>=to_date('20150101','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150801','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150801','yyyymmdd') and sale_date>=to_date('20150201','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20150901','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20150901','yyyymmdd') and sale_date>=to_date('20150301','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20151001','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20151001','yyyymmdd') and sale_date>=to_date('20150401','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20151101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20151101','yyyymmdd') and sale_date>=to_date('20150501','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20151201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20151201','yyyymmdd') and sale_date>=to_date('20150601','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20160101','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20160101','yyyymmdd') and sale_date>=to_date('20150701','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20160201','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20160201','yyyymmdd') and sale_date>=to_date('20150801','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20160301','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped
where sale_date<to_date('20160301','yyyymmdd') and sale_date>=to_date('20150901','yyyymmdd')
group by province_id, city_id;

insert into lagging_feature_noclass_6
select province_id, city_id, to_date('20160401','yyyymmdd') as sale_date,sum(sale_quantity) as nsum_6, avg(sale_quantity) as navg_6,median(sale_quantity) as nmed_6, stddev(sale_quantity) as nstd_6
from yc_car_sales_grouped

In [8]:
df = pd.read_csv('../../holiday.csv')

In [9]:
df['date'] = pd.to_datetime(df['date'],format='%Y%m')

In [10]:
df.head()

,date,holidays,important,spring_month,next_spring,last_spring,nd_month,next_nd,last_nd,labor_month,work_days,newyear_month,next_newyear,last_newyear
0,2012-01-01,7,1,1,0,0,0,0,0,0,16,1,0,0
1,2012-02-01,0,0,0,0,1,0,0,0,0,21,0,0,0
2,2012-03-01,0,0,0,0,0,0,0,0,0,22,0,0,0
3,2012-04-01,4,1,0,0,0,0,0,0,0,21,0,0,0
4,2012-05-01,1,1,0,0,0,0,0,0,1,19,0,0,0

In [11]:
df.shape

(74, 14)

In [21]:
print(pd.io.sql.get_schema(df,'holiday'))

CREATE TABLE "holiday" (
"date" TIMESTAMP,
  "holidays" INTEGER,
  "important" INTEGER,
  "spring_month" INTEGER,
  "next_spring" INTEGER,
  "last_spring" INTEGER,
  "nd_month" INTEGER,
  "next_nd" INTEGER,
  "last_nd" INTEGER,
  "labor_month" INTEGER,
  "work_days" INTEGER,
  "newyear_month" INTEGER,
  "next_newyear" INTEGER,
  "last_newyear" INTEGER
)

In [13]:
print("insert into table holiday values")
for idx, row in df.iterrows():
    print("(datetime'%s', %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d)," 
          %(row['date'],row['holidays'],row['important'], \
          row['spring_month'], row['next_spring'], row['last_spring'], \
          row['nd_month'], row['next_nd'], row['last_nd'], \
            row['labor_month'], row['work_days'], \
           row['newyear_month'], row['next_newyear'], row['last_newyear']))

insert into table holiday values
(datetime'2012-01-01 00:00:00', 7, 1, 1, 0, 0, 0, 0, 0, 0, 16, 1, 0, 0),
(datetime'2012-02-01 00:00:00', 0, 0, 0, 0, 1, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2012-03-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0),
(datetime'2012-04-01 00:00:00', 4, 1, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2012-05-01 00:00:00', 1, 1, 0, 0, 0, 0, 0, 0, 1, 19, 0, 0, 0),
(datetime'2012-06-01 00:00:00', 1, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2012-07-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0),
(datetime'2012-08-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0),
(datetime'2012-09-01 00:00:00', 0, 0, 0, 0, 0, 0, 1, 0, 0, 20, 0, 0, 0),
(datetime'2012-10-01 00:00:00', 5, 1, 0, 0, 0, 1, 0, 0, 0, 20, 0, 0, 0),
(datetime'2012-11-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 1, 0, 22, 0, 0, 0),
(datetime'2012-12-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 1, 0),
(datetime'2013-01-01 00:00:00', 3, 1, 0, 1, 0, 0, 0, 0, 0, 22, 1, 0, 0),
(datetime'2013-02-01 00:00:00', 5, 1, 1, 0, 0, 0, 0, 0, 0, 17, 0, 0, 1),
(datetime'2013-03-01 00:00:00', 0, 0, 0, 0, 1, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2013-04-01 00:00:00', 4, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2013-05-01 00:00:00', 1, 1, 0, 0, 0, 0, 0, 0, 1, 22, 0, 0, 0),
(datetime'2013-06-01 00:00:00', 3, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0, 0),
(datetime'2013-07-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0),
(datetime'2013-08-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0),
(datetime'2013-09-01 00:00:00', 2, 0, 0, 0, 0, 0, 1, 0, 0, 21, 0, 0, 0),
(datetime'2013-10-01 00:00:00', 5, 1, 0, 0, 0, 1, 0, 0, 0, 19, 0, 0, 0),
(datetime'2013-11-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 1, 0, 21, 0, 0, 0),
(datetime'2013-12-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 1, 0),
(datetime'2014-01-01 00:00:00', 2, 1, 0, 1, 0, 0, 0, 0, 0, 22, 1, 0, 0),
(datetime'2014-02-01 00:00:00', 4, 1, 1, 0, 0, 0, 0, 0, 0, 17, 0, 0, 1),
(datetime'2014-03-01 00:00:00', 0, 0, 0, 0, 1, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2014-04-01 00:00:00', 1, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2014-05-01 00:00:00', 2, 1, 0, 0, 0, 0, 0, 0, 1, 21, 0, 0, 0),
(datetime'2014-06-01 00:00:00', 1, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0),
(datetime'2014-07-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0),
(datetime'2014-08-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2014-09-01 00:00:00', 1, 1, 0, 0, 0, 0, 1, 0, 0, 22, 0, 0, 0),
(datetime'2014-10-01 00:00:00', 5, 1, 0, 0, 0, 1, 0, 0, 0, 19, 0, 0, 0),
(datetime'2014-11-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 1, 0, 20, 0, 0, 0),
(datetime'2014-12-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 1, 0),
(datetime'2015-01-01 00:00:00', 2, 1, 0, 1, 0, 0, 0, 0, 0, 21, 1, 0, 0),
(datetime'2015-02-01 00:00:00', 5, 1, 1, 0, 0, 0, 0, 0, 0, 17, 0, 0, 1),
(datetime'2015-03-01 00:00:00', 0, 0, 0, 0, 1, 0, 0, 0, 0, 22, 0, 0, 0),
(datetime'2015-04-01 00:00:00', 1, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2015-05-01 00:00:00', 1, 1, 0, 0, 0, 0, 0, 0, 1, 20, 0, 0, 0),
(datetime'2015-06-01 00:00:00', 1, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2015-07-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0),
(datetime'2015-08-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2015-09-01 00:00:00', 2, 0, 0, 0, 0, 0, 1, 0, 0, 21, 0, 0, 0),
(datetime'2015-10-01 00:00:00', 5, 1, 0, 0, 0, 1, 0, 0, 0, 18, 0, 0, 0),
(datetime'2015-11-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 1, 0, 21, 0, 0, 0),
(datetime'2015-12-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 1, 0),
(datetime'2016-01-01 00:00:00', 1, 0, 0, 1, 0, 0, 0, 0, 0, 20, 1, 0, 0),
(datetime'2016-02-01 00:00:00', 5, 1, 1, 0, 0, 0, 0, 0, 0, 18, 0, 0, 1),
(datetime'2016-03-01 00:00:00', 0, 0, 0, 0, 1, 0, 0, 0, 0, 23, 0, 0, 0),
(datetime'2016-04-01 00:00:00', 1, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0),
(datetime'2016-05-01 00:00:00', 1, 1, 0, 0, 0, 0, 0, 0, 1, 21, 0, 0, 0),
(datetime'2016-06-01 00:00:00', 2, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2016-07-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2016-08-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0),
(datetime'2016-09-01 00:00:00', 2, 1, 0, 0, 0, 0, 1, 0, 0, 21, 0, 0, 0),
(datetime'2016-10-01 00:00:00', 5, 1, 0, 0, 0, 1, 0, 0, 0, 18, 0, 0, 0),
(datetime'2016-11-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 1, 0, 22, 0, 0, 0),
(datetime'2016-12-01 00:00:00', 0, 0, 0, 1, 0, 0, 0, 0, 0, 22, 0, 1, 0),
(datetime'2017-01-01 00:00:00', 4, 1, 1, 0, 0, 0, 0, 0, 0, 19, 1, 0, 0),
(datetime'2017-02-01 00:00:00', 2, 1, 0, 0, 1, 0, 0, 0, 0, 19, 0, 0, 1),
(datetime'2017-03-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0),
(datetime'2017-04-01 00:00:00', 2, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0, 0),
(datetime'2017-05-01 00:00:00', 3, 1, 0, 0, 0, 0, 0, 0, 1, 21, 0, 0, 0),
(datetime'2017-06-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0),
(datetime'2017-07-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0),
(datetime'2017-08-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0),
(datetime'2017-09-01 00:00:00', 0, 0, 0, 0, 0, 0, 1, 0, 0, 22, 0, 0, 0),
(datetime'2017-10-01 00:00:00', 5, 1, 0, 0, 0, 1, 0, 0, 0, 17, 0, 0, 0),
(datetime'2017-11-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 1, 0, 22, 0, 0, 0),
(datetime'2017-12-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 1, 0),
(datetime'2018-01-01 00:00:00', 1, 1, 0, 1, 0, 0, 0, 0, 0, 22, 1, 0, 0),
(datetime'2018-02-01 00:00:00', 4, 1, 1, 0, 0, 0, 0, 0, 0, 16, 0, 0, 1),

In [ ]:
year_total = {2012:35415853,
              2013:42592538,
              2014:49950026,
              2015:57342964,
              2016:70528212,
              2017:72582555,
              2018:74760000}
year_growth = {2012:1,
               2013:1.2,
               2014:1.17,
               2015:1.15,
               2016:1.23,
               2017:1.029,
               2018:1.029}

ratio_avg = {1:0.09,
             2:0.063,
             3:0.073,
             4:0.071,
             5:0.077,
             6:0.068,
             7:0.076,
             8:0.0784,
             9:0.0907,
             10:0.0876,
             11:0.094,
             12:0.12}

ratio_max = {1:0.1,
             2:0.084,
             3:0.08,
             4:0.065,
             5:0.071,
             6:0.066,
             7:0.072,
             8:0.0703,
             9:0.0947,
             10:0.086,
             11:0.102,
             12:0.14}

ratio_min = {1:0.08,
             2:0.047,
             3:0.07,
             4:0.079,
             5:0.083,
             6:0.072,
             7:0.079,
             8:0.086,
             9:0.0843,
             10:0.090,
             11:0.084,
             12:0.093}

for year in range(2012,2019):
    for month in range(1,13):
        d = date(year,month,1)
        d3 = d+DateOffset(months=-1)
        d2 = d+DateOffset(months=-(offset+1))
        print('insert into re_year values')
        print("select province_id, city_id, class_id, to_date('%s','yyyymmdd') as sale_date, avg(sale_quantity) as avg_%d,median(sale_quantity) as med_%d, max(sale_quantity) as max_%d, min(sale_quantity) as min_%d,stddev(sale_quantity) as std_%d, count(sale_quantity) as count_%d" \
             %(d.strftime(format='%Y%m%d'), offset,offset,offset,offset,offset,offset))
        print('from yc_car_sales_grouped a')
        print("where a.sale_date<to_date('%s','yyyymmdd') and a.sale_date>=to_date('%s','yyyymmdd')"%(d3.strftime(format='%Y%m%d'),d2.strftime(format='%Y%m%d')))
        print("group by province_id, city_id, class_id;\n")
        counter+=1
        
        if year==2018 and month==2:
            break